local builtin = require('telescope.builtin')
local utils = require('utils')

utils.nmap('<leader>fb', ':Telescope file_browser path=%:p:h select_buffer=true<CR>', '[S]earch [F]iles')
utils.nmap('<leader>sf', builtin.find_files, '[S]earch [F]iles')
utils.nmap('<leader>sgf', builtin.git_files, '[S]earch [G]it [F]iles')
utils.nmap('<leader>sh', builtin.help_tags, '[S]earch [H]elp')
utils.nmap('<leader>sw', builtin.grep_string, '[S]earch current [W]ord')
utils.nmap('<leader>sg', builtin.live_grep, '[S]earch by [G]rep')
utils.nmap('<leader>sd', builtin.diagnostics, '[S]earch [D]iagnostics')
utils.nmap('<leader>sk', builtin.keymaps, '[S]earch [K]eymaps')
utils.nmap('<leader>sm', builtin.man_pages, '[S]earch [M]an' )
utils.nmap('<leader>sm', builtin.man_pages, '[S]earch [M]an' )
utils.nmap('<leader>?', builtin.oldfiles, '[?] Find recently opened files')
