local builtin = require('telescope.builtin')

Nmap('<leader>sf', builtin.find_files, '[S]earch [F]iles')
Nmap('<leader>sgf', builtin.git_files, '[S]earch [G]it [F]iles')
Nmap('<leader>sh', builtin.help_tags, '[S]earch [H]elp')
Nmap('<leader>sw', builtin.grep_string, '[S]earch current [W]ord')
Nmap('<leader>sg', builtin.live_grep, '[S]earch by [G]rep')
Nmap('<leader>sd', builtin.diagnostics, '[S]earch [D]iagnostics')
Nmap('<leader>sk', builtin.keymaps, '[S]earch [K]eymaps')
Nmap('<leader>sm', builtin.man_pages, '[S]earch [M]an' )
Nmap('<leader>?', builtin.old_filfs, '[?] Find recently opened files')
